

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: node-express-namespace

spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username

        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password        

        volumeMounts:
          - name: mongo-storage
            mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: node-express-namespace
  labels:
    app: mongodb

spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP 
      port: 27017
      targetPort: 27017
  clusterIP: None    
             
  
