

apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-volume

spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""    
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /usr/local/mongo-db    


