apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: node-express-namespace   
spec:
  accessModes:
    - ReadWriteOnce                 
  resources:
    requests:
      storage: 1Gi                    
  storageClassName: ""                

